spring:
  profiles:
    active: dev  # 默认激活开发环境配置

# 通用配置
server:
  port: 8080  # 应用端口
  servlet:
    context-path: /  # 应用根路径

# 微信小程序配置
wx:
  appid: wx6c86e9c57783bbb0  # 与前端project.config.json中的appid保持一致
  secret: 9fbb16113d4e2cc252251a88b9a4a295  # 测试用secret，真实场景需替换

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # MyBatis XML映射文件位置
  type-aliases-package: com.book.chat.entity # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰命名
    cache-enabled: false  # 关闭缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出SQL日志
  global-config:
    db-config:
      id-type: AUTO  # 主键策略
      table-prefix: t_  # 表前缀

# 日志配置
logging:
  level:
    root: INFO
    com.book.chat: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

# 应用自定义配置
app:
  jwt:
    secret: YourJwtSecretKeyHereMustBeAtLeast32BytesLong  # JWT密钥
    expiration: 86400000  # Token有效期，单位毫秒，默认24小时
  llm:
    # LLM服务提供商，可选值：deepseek, qwen
    provider: deepseek
    # DeepSeek API配置
    deepseek:
      api-url: https://api.deepseek.com/chat/completions  # 根据文档修改回原API地址
      api-key: sk-449482b902174ba4be734c0ad8ea2863  # DeepSeek API密钥
      model: deepseek-chat  # DeepSeek模型名称
    # 通义千问API配置  
    qwen:
      api-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions  # 通义千问兼容模式API地址
      api-key: your_qwen_api_key  # 通义千问API密钥
      model: qwen-plus  # 通义千问模型名称
    timeout: 30000  # API调用超时时间，单位毫秒
